#!/usr/bin/env bash
# Displays information about subdomains, if no domain
# then www, lb-01, web-01, web-02, in that order.
# shellcheck disable=SC2086
dom="$1"


if [ "$#" -eq 2 ]
then
	sub=$2
elif [ "$#" -eq 1 ]
then
	sub=("www" "lb-01" "web-01" "web-02")
fi
for s in "${sub[@]}"
do
	echo -n "The subdomain $s"
	dig "$s.$1" | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk '{print " is a "$4 " record and points to " $5}'
done
