#!/usr/bin/env bash
# Install nginx on yo web-01 server, listening on port 80
# When queried at root with a GET request, must contain Holberton School stri
sudo apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/index.html
sudo echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
