#!/usr/bin/env bash
#  Configure a new web server
#  With custom HTTP Header

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
