#!/usr/bin/env bash
# Install nginx on yo web-01 server
# And configures /redirect_me to redirect to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Holberton School" | /var/www/html/index.html
sudo sed -i '/server_name _/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | /var/www/html/custom_404.html
sudo sed -i '/server_name _/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo sed -i "36a \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
