#!/usr/bin/env bash
#  set up HAproxy load balancer! DON'T FUCK UP THIS TIME

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" | tee -a /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
echo "listen www
    bind :80
    server 1692-web-01 34.228.186.149:80 check
    server 1692-web-02 34.73.35.13:80 check" | tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
