#!/usr/bin/env bash
#  set up HAproxy load balancer!

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo echo "listen www
    bind :80
    server gc-1692-web-01-1596432771 34.75.121.144:80 check
    server 1692-web-02 54.227.55.35:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
