#!/usr/bin/env bash
# Silly loop script.
echo $$ > /var/run/holbertonscript.pid
trap termy 15
trap inty 2
trap quity 3
termy()
{
	echo "I hate the kill command"
	rm /var/run/holbertonscript.pid
	exit 1
}
inty()
{
	echo "Y U no love me?!"
	exit 1
}
quity()
{
	rm /var/run/holbertonscript.pid
	exit 1
}
while true
do
	echo "To infinity and beyond"
	sleep 2
done
