#!/usr/bin/env bash
# Fizzbuzz!!
i=1
maxi=100
while [ $i -le $maxi ]
do
	if ! ((i % 3)) && ! ((i % 5))
	then
			echo "FizzBuzz"
	elif ! ((i % 3))
	then
			echo "Fizz"
	elif ! ((i % 5))
	then
			echo "Buzz"
	else
			echo "$i"
	fi
	i=$((i+1))
done
