#!/usr/bin/env bash
# Displays Holberton School 10 times
START=1
x=$START
while [ $x -ne 11 ]
do
	if [ $x = 4 ]
	then
		echo "bad luck"
	elif [ $x = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	x=$((x+1))
done
