#!/usr/bin/env bash
# Displays Holberton School 10 times
START=1
x=$START
while [ $x -ne 21 ]
do
	if [ $x = 4 ]
	then
		echo $x
		echo "bad luck from China"
	elif [ $x = 9 ]
	then
		echo $x
		echo "bad luck from Japan"
	elif [ $x = 17 ]
	then
		echo $x
		echo "bad luck from Italy"
	else
		echo $x
	fi
	x=$((x+1))
done
