#!/usr/bin/env bash
# Displays Holberton School 10 times
START=1
x=$START
while [ $x -ne 21 ]
do
	case $x in
		4)
			echo $x
			echo "bad luck from China"
			;;
		9)
			echo $x
			echo "bad luck from Japan"
			;;
		17)
			echo $x
			echo "bad luck from Italy"
			;;
		*)
			echo $x
			;;
	esac
	x=$((x+1))
done
