#!/usr/bin/env bash
# Updates /etc/hosts for overriding DNS of localhost & facebook
cp /etc/hosts ~/hosts.new
sed -i "/localhost$/ { c \
127.0.0.2 localhost
}" ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
