#!/usr/bin/env bash
# MAKE NGINX RUN AS NGINX(USER)
pkill apache2
pkill nginx
chmod -R 777 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/nginx.conf
sed -i '1a user nginx;' /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
service nginx restart
